### PR TITLE
#4 add Favicon index.html

### PR DESCRIPTION
**Pull request by MRidwanKurniawan**
#14 adding Favicon.. :D

### CODE REVIEW

**Comment by nitinkgp23** [comment]
Hey @butuh , thanks a lot for the PR! Could you please use a favicon related to 'mathematics'? That would be more relevant to the website we are building. :)

**Comment by MRidwanKurniawan** [comment]
hi i use this 
favicon
 and I had upload to favicon.ico

**Comment by Parth-Vader** [comment]
I think this suits us. @nitinkgp23 ?

**Comment by nitinkgp23** [comment]
Thanks a lot @butuh for the PR!

**Pull request merged**
